# Generated by Django 3.1.7 on 2021-03-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_accounts',
            new_name='SocialAccounts',
        ),
    ]
