# Generated by Django 3.1.7 on 2021-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(upload_to='home/static/home/images/carousel'),
        ),
    ]
