# Generated by Django 3.1.7 on 2021-03-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210314_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(upload_to='home/static/home/'),
        ),
    ]
