# Generated by Django 3.1.7 on 2021-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210314_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
