# Generated by Django 3.1.7 on 2021-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210314_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
